In [2]:
import numpy as np

a = np.array([1,2,3]) # Tạo mảng 1 chiều
print(type(a)) # Kiểu dữ liệu
print(a.shape) # Kích thước mảng
print(a[0], a[1], a[2]) # Truy cập phần tử
# a[0] = 5 # Thay đổi giá trị phần tử
# print(a)
# Numpy arrays hỗ trợ nhiều hàm toán học
print(np.sum(a)) # Tổng các phần tử
print(np.mean(a)) # Giá trị trung bình
print(np.std(a)) # Độ lệch chuẩn

<class 'numpy.ndarray'>
(3,)
1 2 3
6
2.0
0.816496580927726


In [4]:
b = np.array([[1,2,3],[4,5,6]]) # Tạo mảng 2 chiều
print(b.shape) # Kích thước mảng
print(b[0,0], b[0,1], b[1,0]) # Truy cập phần tử
b[0,0] = 9 # Thay đổi giá trị phần tử
print(b)
# Numpy arrays hỗ trợ nhiều hàm toán học
print(np.max(b)) # Giá trị lớn nhất
print(np.min(b)) # Giá trị nhỏ nhất

(2, 3)
1 2 4
[[9 2 3]
 [4 5 6]]
9
2


In [8]:
b = np.zeros((2,3)) # Tạo mảng 2 chiều toàn số 0
print(b)
c = np.ones((3,4)) # Tạo mảng 3 chiều toàn số 1
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
print(np.diag([1, 3, 4])) # Lấy đường chéo chính

[[1 0 0]
 [0 3 0]
 [0 0 4]]


In [13]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.diag(b))      # lấy đường chéo chính
print(np.diag(b, 1))   # lấy đường chéo trên
print(np.diag(b, -1))  # lấy đường chéo dưới

[1 5 9]
[2 6]
[4 8]


In [ ]:
arr1 = np.arange(0,10,2)
print(arr1) # Tạo mảng từ 0 đến 10, bước nhảy 2
arr2 = np.arange(0,10,1.5)
print(arr2) # Tạo mảng từ 0 đến 10, bước nhảy 1.5

[0 2 4 6 8]
[0.  1.5 3.  4.5 6.  7.5 9. ]


In [18]:
arr3 = np.linspace(0,1,5)
print(arr3) # Tạo mảng từ 0 đến 1, gồm 5 phần tử

[0.   0.25 0.5  0.75 1.  ]


In [20]:
# data = np.random.randn(2,3) # Tạo mảng 2 chiều với các phần tử ngẫu nhiên
data = np.array([1,1,2,3,3,3,4,5,5])
hist, bin_edges = np.histogram(data, bins=5) # Tạo histogram với 5 bins
print("Data:\n", data)
print("Histogram:\n", hist)
print("Bin edges:\n", bin_edges)

Data:
 [1 1 2 3 3 3 4 5 5]
Histogram:
 [2 1 3 1 2]
Bin edges:
 [1.  1.8 2.6 3.4 4.2 5. ]


In [21]:
A = np.array([[1,2],[3,4]])
print(np.linalg.inv(A)) # Ma trận nghịch đảo của ma trận vuông
print(np.linalg.det(A)) # Định thức của ma trận

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [23]:
x = np.array([0,1,2,3])
y = np.array([1,2,3,5])
coeffs = np.polyfit(x, y, 1) # Hồi quy đa thức bậc 1 (tuyến tính)
print("Coefficients:", coeffs)

Coefficients: [1.3 0.8]


In [33]:
np.eye(3) # Ma trận đơn vị 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,5) # Ma trận đơn vị 3x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
np.eye(4, k=1) # Ma trận đơn vị 4x4, dịch chuyển đường chéo chính lên trên 1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [38]:
np.eye(4, k=-1) # Ma trận đơn vị 4x4, dịch chuyển đường chéo chính xuống dưới 1

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
np.eye(3, dtype=int) # Ma trận đơn vị 3x3, kiểu int

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
a = np.arange(12)
# a.reshape(3,4) # Chuyển đổi mảng 1 chiều thành mảng 2 chiều 3x4
# a.reshape(3,4, order='F') # Chuyển đổi mảng 1 chiều thành mảng 2 chiều 3x4 theo cột
a.reshape(2,-1) # Tự động tính toán kích thước chiều còn lại

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
a = np.array([[1,2,3],[4,5,6]])
# print(a.ravel()) # Chuyển đổi mảng nhiều chiều thành mảng 1 chiều
# print(a.flatten()) # Chuyển đổi mảng nhiều chiều thành mảng 1 chiều, tương tự như ravel nhưng luôn trả về bản sao
# print(a.T) # Chuyển vị ma trận
np.transpose(a) # Chuyển vị ma trận, tương tự như a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# c = np.vstack((a,b)) # Ghép mảng theo chiều dọc
# c = np.hstack((a,b)) # Ghép mảng theo chiều ngang
c = np.concatenate((a,b)) # Ghép mảng theo chiều ngang chỉ 1 chiều
print(c)

[1 2 3 4 5 6]


In [51]:
a = np.array([[1,2],[3,4]])
b  = np.array([[5,6]])

print(np.concatenate((a,b), axis=0)) # Ghép theo chiều dọc

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([[1,2],[3,4]])
b  = np.array([[5],[6]])
print(np.concatenate((a,b), axis=1)) # Ghép theo chiều ngang theo 2 chiều

[[1 2 5]
 [3 4 6]]


In [12]:
a = np.arange(9)
# parts = np.array_split(a, 3) # Chia mảng thành 3 phần
parts = np.split(a, 3) # Chia mảng thành 3 phần đều nhau
print(parts)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [13]:
x = np.array([1,2,3])
y = np.array([4,5,6])

res = np.dot(x, y) # Tích vô hướng
print(res)

32


In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A, B) # Tích ma trận
print(C)

[[19 22]
 [43 50]]


In [18]:
# print(np.multiply(A, B)) # Nhân phần tử tương ứng
print(np.matmul(A, B)) # Tích ma trận, tương tự như np.dot(A, B)
print(A @ B) # Tích ma trận, tương tự như np.dot(A, B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [19]:
a = np.array([1,2,2,3,4,4,4,5])
print(np.unique(a)) # Các phần tử duy nhất trong mảng

[1 2 3 4 5]


In [20]:
vals, index = np.unique(a, return_inverse=True) # Các phần tử duy nhất và chỉ số của chúng trong mảng ban đầu
print("Unique values:", vals) # Các phần tử duy nhất
print("Indices:", index) # Chỉ số của các phần tử duy nhất trong mảng

Unique values: [1 2 3 4 5]
Indices: [0 1 1 2 3 3 3 4]


In [21]:
a = np.array([10, 20, 30, 40, 50])
idx = np.where(a > 25) # Chỉ số các phần tử lớn hơn 25
print("Indices:", idx)
print("Values:", a[idx])

Indices: (array([2, 3, 4]),)
Values: [30 40 50]


In [24]:
# res = np.nonzero(a > 25) # Chỉ số các phần tử lớn hơn 25
res = np.where(a > 25, a*2, -1) # Nếu chỉ số các phần tử lớn hơn 25 thì gán giá trị a*2, ngược lại gán -1
print(res)

[ -1  -1  60  80 100]


In [31]:
A = np.array([[4, -2], [1, 1]])
w, v = np.linalg.eig(A) # Tính giá trị riêng và vectơ riêng của ma trận
print(np.unique(A))
print(np.unique(w))
print(np.unique(v))
print(type(w), type(v))
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)

[-2  1  4]
[2. 3.]
[0.4472136  0.70710678 0.89442719]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
