In [ ]:
# 1. Tạo vector 1 chiều và thực hiện các phép toán
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Cộng:", a + b)
print("Trừ:", a - b)
print("Nhân:", a * b)
print("Chia:", a / b)
print("Lũy thừa:", a ** 2)
print("Căn bậc hai:", np.sqrt(a))
print("Logarit:", np.log(a))
print("Tổng:", np.sum(a))

Cộng: [5 7 9]
Trừ: [-3 -3 -3]
Nhân: [ 4 10 18]
Chia: [0.25 0.4  0.5 ]
Lũy thừa: [1 4 9]
Căn bậc hai: [1.         1.41421356 1.73205081]
Logarit: [0.         0.69314718 1.09861229]
Tổng: 6


In [ ]:
# print("Determinant:", np.linalg.det(np.array([[1,2],[3,4]])))
# print("Inverse:\n", np.linalg.inv(np.array([[1,2],[3,4]])))
# print("Rank:", np.linalg.matrix_rank(np.array([[1,2],[3,4]])))
# print("SVD:\n", np.linalg.svd(np.array([[1,2],[3,4]])))
# print("Cholesky:\n", np.linalg.cholesky(np.array([[4,2],[2,3]])))
# print("QR Decomposition:\n", np.linalg.qr(np.array([[1,2],[3,4]])))
# print("Norm:", np.linalg.norm(np.array([[1,2],[3,4]])))
# print("Solve Ax = b:", np.linalg.solve(np.array([[1,2],[3,4]]), np.array([5,11])))
# print("Eigenvalues and Eigenvectors:", np.linalg.eig(np.array([[1,2],[3,4]])))
# print("Matrix Exponential:\n", np.linalg.expm(np.array([[1,2],[3,4]])))

In [ ]:
A = np.array([[4, -2], [1, 1]])
w, v = np.linalg.eig(A) # Tính giá trị riêng và vectơ riêng của ma trận vuông
print(np.unique(A))
print(np.unique(w))
print(np.unique(v))
print(type(w), type(v))
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)

[-2  1  4]
[2. 3.]
[0.4472136  0.70710678 0.89442719]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
# 2. Tích vô hướng (dot product) 2 vector
print("Tích vô hướng:", np.dot(a, b))

Tích vô hướng: 32


In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("A * B =\n", A * B)  # Phép nhân phần tử
print("A / B =\n", A / B)  # Phép chia phần tử
print("A @ B =\n", A @ B)  # Phép nhân ma trận hoặc dùng np.matmul(A, B)
print("A / B =\n", np.linalg.solve(B.T, A.T).T)  # Phép chia 2 ma trận

A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]
A * B =
 [[ 5 12]
 [21 32]]
A / B =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
A @ B =
 [[19 22]
 [43 50]]
A / B =
 [[ 3. -2.]
 [ 2. -1.]]


In [14]:
# 3. Ma trận chuyển vị
print("A.T =\n", A.T)
print("B.T =\n", B.T)

A.T =
 [[1 3]
 [2 4]]
B.T =
 [[5 7]
 [6 8]]


In [15]:
# 4. Lấy 1 dòng / 1 cột của ma trận
print("Dòng 0 của A:", A[0, :])
print("Cột 1 của A:", A[:, 1])
print("Dòng 1 của B:", B[1]) 

Dòng 0 của A: [1 2]
Cột 1 của A: [2 4]
Dòng 1 của B: [7 8]


In [16]:
# 5. Tính định thức ma trận
print("Determinant of A:", np.linalg.det(A))
print("Determinant of B:", np.linalg.det(B))

Determinant of A: -2.0000000000000004
Determinant of B: -2.000000000000005


In [ ]:
a = np.arange(10) # nên cho tổng số phần tử chẵn
# a.reshape(3,4) # Chuyển đổi mảng 1 chiều thành mảng 2 chiều 3x4
# a.reshape(3,4, order='F') # Chuyển đổi mảng 1 chiều thành mảng 2 chiều 3x4 theo cột
a.reshape(2,-1) # Tự động tính toán kích thước chiều còn lại, có 2 hàng mỗi hàng 5 phần tử, -1 là để numpy tự tính số cột

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
# 6. Nối và tách mảng
C = np.concatenate((A, B), axis=0)
print("C =\n", C)
print("C[:2] =\n", C[:2]) # Lấy 2 dòng đầu
print("C[2:] =\n", C[2:]) # Lấy 2 dòng cuối

tach1, tach2 = np.split(C, 2, axis=0) # Tách C thành 2 mảng theo chiều dọc
print("tach1 =\n", tach1)
print("tach2 =\n", tach2)

C =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
C[:2] =
 [[1 2]
 [3 4]]
C[2:] =
 [[5 6]
 [7 8]]
tach1 =
 [[1 2]
 [3 4]]
tach2 =
 [[5 6]
 [7 8]]


In [ ]:
# 7. Ghép mảng
a = np.array([[1,2],[3,4]])
b  = np.array([[5],[6]])
c = np.concatenate((a, b), axis=1)
print("c =\n", c) # Ghép theo chiều ngang theo 2 chiều

c =
 [[1 2 5]
 [3 4 6]]


In [23]:
# 8. Sinh ma trận random
rand_mat = np.random.randint(0, 10, (3, 3))  # 3x3 số nguyên [0,10)
print("Ma trận ngẫu nhiên:\n", rand_mat)

Ma trận ngẫu nhiên:
 [[6 6 3]
 [6 9 5]
 [8 8 2]]


In [24]:
# 9. Ma trận 3 chiều và tính tổng theo trục
tensor = np.random.randint(1, 5, (2, 3, 4))  # 2 ma trận 3x4
print("Tensor:\n", tensor)

print("Tổng theo trục 0 (gộp theo ma trận):\n", np.sum(tensor, axis=0))
print("Tổng theo trục 1 (gộp theo hàng):\n", np.sum(tensor, axis=1))

Tensor:
 [[[1 2 3 4]
  [4 4 4 1]
  [3 1 2 2]]

 [[2 3 1 4]
  [3 2 4 1]
  [3 1 2 4]]]
Tổng theo trục 0 (gộp theo ma trận):
 [[3 5 4 8]
 [7 6 8 2]
 [6 2 4 6]]
Tổng theo trục 1 (gộp theo hàng):
 [[8 7 9 7]
 [8 6 7 9]]


In [26]:
# 10. Hồi quy đa thức bậc 1 (tuyến tính)
x = np.array([1, 2, 3, 4, 5])
y = np.array([2.2, 2.8, 3.6, 4.5, 5.1])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
print("Hệ số góc m:", m)
print("Hệ số chặn c:", c)
print("Phương trình hồi quy: y = {:.2f}x + {:.2f}".format(m, c))
coeffs = np.polyfit(x, y, 1) # Hồi quy đa thức bậc 1 (tuyến tính)
print("Coefficients:", coeffs)

Hệ số góc m: 0.7499999999999999
Hệ số chặn c: 1.3899999999999992
Phương trình hồi quy: y = 0.75x + 1.39
Coefficients: [0.75 1.39]
